<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fcc6fa5b-0aa2-4f54-a30a-f9dfa54def10</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_31</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[6]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'QE Automation')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>QE Automation</value>
        <webElementGuid>1788fbe1-f951-4eb0-aaf3-15411d2ed389</webElementGuid>
    </webElementProperties>
</WebElementEntity>