<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>737a8661-ff41-49ff-ba96-021803653fe2</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_61</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[3]/ul[1]/li[2]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>