<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bdd10d2e-1205-4531-bc24-d1e7e5536089</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_46</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[4]/span[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'AC-ST045119 Verify user cannot assign invalid or duplicate custom field')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>AC-ST045119 Verify user cannot assign invalid or duplicate custom field</value>
        <webElementGuid>8968c7dd-479d-472a-b463-d26cb31e4f65</webElementGuid>
    </webElementProperties>
</WebElementEntity>