<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>429d104a-7320-42f0-b92a-2866e1e1da63</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_73</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/div[1]/form[1]/div[1]/div[3]/div[3]/table[1]/tbody[1]/tr[5]/td[3]/div[1]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'git-test-sample/Test Cases/Common Test Cases')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>git-test-sample/Test Cases/Common Test Cases</value>
        <webElementGuid>d77c0eb2-e28c-43e6-9060-1e65994ba577</webElementGuid>
    </webElementProperties>
</WebElementEntity>