<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>105fc25d-4a5e-4ec6-b945-a82d06a6ba58</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[3]/nav[1]/div[1]/ul[1]/a[8]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Configure properties for autonomous testing.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Configure properties for autonomous testing.</value>
        <webElementGuid>e28af00c-631e-4e36-9ac9-b505177a251b</webElementGuid>
    </webElementProperties>
</WebElementEntity>